#!/bin/bash
# A collection of setup scripts

# Install Vim-Plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

touch ~/.vimrc
echo "source ~/etc/vimconfig.vim" >> ~/.vimrc

touch ~/.bash_profile
echo "source ~/etc/bashrc" >> ~/.bash_profile
