#!/bin/bash
# A collection of setup ecripts

# Tmux
# Add bash profile to home directory, reference dotfile bashrc
touch ~/.bash_profile
echo "source ~/.dotfiles/bashrc" >> ~/.bash_profile

sudo apt-get update

# Install NeoVim
sudo apt-get install vim -y
sudo apt-get install silversearcher-ag

# Tmux
sudo apt-get install tmux -y
touch ~/.tmux.conf
echo "source-file ~/.dotfiles/tmux.conf" >> ~/.tmux.conf

# Install Vim-Plug for NeoVim
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Copy over vim config
echo "source ~/.dotfiles/vimconfig.vim" >> ~/.vimrc
