#!/bin/bash
# A collection of setup ecripts

# Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Rbenv
brew install rbenv && rbenv init

# Tmux
# brew install tmux
touch ~/.tmux.conf
echo "source-file ~/.dotfiles/tmux.conf" >> ~/.tmux.conf

# Add bash profile to home directory, reference dotfile bashrc
touch ~/.bash_profile
echo "source ~/.dotfiles/bashrc" >> ~/.bash_profile

# Install NeoVim
brew install neovim

brew install the_silver_searcher

# Install Vim-Plug for NeoVim
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
   https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Copy over vim config to
mkdir -p ~/.config/ && mkdir -p ~/.config/nvim && touch ~/.config/nvim/init.vim
echo "source ~/.dotfiles/vimconfig.vim" >> ~/.config/nvim/init.vim

# Install Powerline Fonts
git clone https://github.com/powerline/fonts.git
# install
cd fonts
./install.sh
# clean-up a bit
cd ..
rm -rf fonts
